name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build .  --tag my-image-name:$(date +%s)
      run:  docker build .  --tag java-operator-sample

#docker build -t java-operator-sample  -f ./Dockerfile .
